### ISSUE TITLE
Update README to reference body element, rather than html element

### ISSUE THREAD

**Issue by bglw** [memob0x/scroll-padlock#11]
Following through the README, the guidance is to use `const { documentElement } = document;` and set your styles at `html.your-locked-class`. Implementing that, I saw that the CSS variables were still being applied to the `body` element, and indeed looking at the [vanilla demo](https://rgzrb.csb.app/) I see that everything there is applied to the `body`. 

Changing my JS & CSS to target `body` rather than `html` made everything work correctly. Unsure whether the `html` path should work, but a quick solution would be to change the docs from [Usage](https://www.npmjs.com/package/scroll-padlock#Usage) down to use `body`.

(Also, nice solution, thanks for the library ❤️)

**Comment by memob0x** [comment]
Hi @bglw, thank you for using this library and for bringing this point to attention.

In the past, some browsers designated `html` to be the default scrollable element while others used `body`, but it looks like a standardization process is taking place towards [`html`](https://developer.mozilla.org/en-US/docs/Web/API/document/scrollingElement), and that's why I think this library default target element should shift from `body` to `html`.

I also think that anyone should be able to use both `html` or `body` if they want to.

I'm currently working on a release that would allow all of this.

I'm also going to split the "Usage" paragraph in the README file into "basic"/"advanced" sections in oder to make the default behavior more clear, as you correctly pointed out.

I'll let you know when the new release will be out...

**Comment by memob0x** [comment]
Hi @bglw.
I just released a new library version (which can be tested [here](https://ztj0wr.csb.app/)).

Let me know if everything is sorted out now.
