### ISSUE TITLE
Can't install package from npm

### ISSUE THREAD

**Issue by dattm97** [memob0x/scroll-padlock#4]
I enter command 'npm install @memob0x/body-scroll-lock' but has error ''@memob0x/body-scroll-lock@1.0.0' is not in the npm registry'

**Comment by memob0x** [comment]
It appears that what is published on github registry is not published on npmjs registry as I initially thought, I'm sorry for that, it seems I forgot to test that out before the release...

At that point I tried to publish the package on npmjs registry directly, but 'body-scroll-lock' name was already taken, so I thought it was the time for a repository rename; in the end, since v1.0, the library class itself is exported as `ScrollPadlock` so...

...you can prompt `npm install scroll-padlock` as of now. 

Again, sorry for the inconvenience, and thank you for pointing this out.

Also, this is my first issue ever so let me know if everything is working fine for you 👍

**Comment by dattm97** [comment]
I installed library from npm. Thanks. But how can i import library to ReactJS project?

**Comment by memob0x** [comment]
Since React is usually transpiled, I think you should import the esm version (_dist/es/scroll-padlock.js_).

Generally speaking you can use any vanilla library you want with any reactive framework, just remember to "cleanup" everything when the component where the library is involved gets unmounted in order to avoid [memory leaks](https://it.reactjs.org/docs/integrating-with-other-libraries.html#integrating-with-dom-manipulation-plugins).

I should definitely add some examples in the README.md of the next minor, in the meantime here's a Vue example (concept is the same for every framework I know):

```javascript
import ScrollPadlock from 'path/to/scroll-padlock.js';

export default {
  name: 'your-scrollable-component',

  data: () => ({
    // padlock instance reference
    scrollPadlock: null
  }),

  /**
   * component mounted hook
   * component DOM is ready
   */
  mounted(){
    // the scrollable element ref
    // (depending on the framework you're using, you can use Refs or traverse the DOM to get the component scrollable element)
    const target = this.$refs.scrollable; // document.querySelector('#scrollable'):

    // sets a padlock instance
    this.scrollPadlock = new ScrollPadlock(target);
  },

  /**
   * component destroyed hook
   */
  destroyed(){
    // detaches the library events avoiding memory leaks
    this.scrollPadlock.destroy();

    // sets the instance reference to its initial state (for clearness and test purposes)
    this.scrollPadlock = null;
  }
};
```

Feel free to open a dedicated issue if you encounter other problems :)

**Comment by memob0x** [comment]
Hi @dattm97 ,
I just provided a React demo https://vouoz.csb.app/ , hope you'll find it useful.

Bye
